/*
HALOMD_MAP_NAMES.H

HaloMD's maps' names, by their files' names (ui_map_list.c), as HaloMD's
public mod list names them. Written by tools/halomd_map_names.py; not
edited by hand.
*/

static struct
{
	char const *file;
	wchar_t const *name;
} const halomd_map_names[] =
{
	{ "3rdperson_2", L"3rd Person" },
	{ "a30_8", L"Halo: The Multiplayer Experience" },
	{ "a30bg_1", L"Halo: The Multiplayer Experience" },
	{ "a30bg_3", L"Halo: The Multiplayer Experience" },
	{ "a30multi_3", L"A30 Multiplayer" },
	{ "a30reflect_1", L"A30 Reflection" },
	{ "a30reflect_2", L"A30 Reflection" },
	{ "a30reflect_7", L"A30 Reflection" },
	{ "acrophobia_1", L"Acrophobia" },
	{ "alienhome_1", L"Alien Homeworld" },
	{ "alternate_1", L"Alternate Universe" },
	{ "ambushed_1", L"Ambushed" },
	{ "ascension_1", L"Ascension" },
	{ "aurtle_1", L"Aureole TLE" },
	{ "aurtle_2", L"Aureole TLE" },
	{ "battle_1", L"BattleGround" },
	{ "battledojo_1", L"BattleDojo" },
	{ "beaverc_1", L"Beaver Creek MD" },
	{ "beaverc_2", L"Beaver Creek MD" },
	{ "bgextreme_10", L"Bloodgulch Extreme" },
	{ "bgplus_2", L"Bloodgulch+" },
	{ "bgplus_3", L"Bloodgulch+" },
	{ "bgplus_4", L"Bloodgulch+" },
	{ "bgplus_5", L"Bloodgulch+" },
	{ "bgulch_1", L"BattleGulch" },
	{ "bigass_aurora_1", L"Bigass Aurora" },
	{ "bigass_aurora_2", L"Bigass Aurora" },
	{ "bigasschrist_1", L"Bigass Christmas" },
	{ "bigasscv2_2", L"Bigass +HUD" },
	{ "bigassfin_1", L"Bigass Final" },
	{ "bigassv2_1", L"Bigass" },
	{ "bigassv2_2", L"Bigass" },
	{ "bigassv3_1", L"Bigass v3" },
	{ "bigassv4_1", L"Bigass v4 [Alpha]" },
	{ "bigassv5_1", L"Bigass v5" },
	{ "blademle_1", L"\x00df" L"lade's Melee War" },
	{ "blizzard_2", L"Blizzard" },
	{ "blood_svi_1", L"BG SpartanVI" },
	{ "bloodextrme_5", L"Bloodgulch Extreme" },
	{ "bloodextrme_6", L"Bloodgulch Extreme" },
	{ "bloodextrme_7", L"Bloodgulch Extreme" },
	{ "bloodextrme_8", L"Bloodgulch Extreme" },
	{ "bloodgulcx_1", L"Bloodgulch X" },
	{ "bloodrev_1", L"Bloodgulch Revised" },
	{ "bombrun4k_1", L"Bomb Run 4K" },
	{ "bombwalk_4k_144hz_basebuilder_2", L"Bomb Walk 4K 144 Hz Basebuilder" },
	{ "bombwalk_4k_144hz_basebuilder_3", L"Bomb Walk 4K 144 Hz Basebuilder" },
	{ "bot300_1", L"Battle of the 300" },
	{ "bot300_2", L"Battle of the 300" },
	{ "bridge_4", L"Pyrhex Bridge" },
	{ "bridgeops_2", L"Bridge Ops" },
	{ "bridgex_1", L"Pyrhex Bridge X" },
	{ "bumpcars_1", L"Bumper Cars" },
	{ "bumpcars_2", L"Bumper Cars" },
	{ "bune_1", L"Bune" },
	{ "canopy_1", L"Canopy" },
	{ "canopy_2", L"Canopy" },
	{ "canopy_3", L"Canopy" },
	{ "canopy_4", L"Canopy" },
	{ "canopy_5", L"Canopy" },
	{ "carnage_1", L"Carnage Mod" },
	{ "carnage_2", L"Carnage Mod" },
	{ "carnage_3", L"Carnage Mod" },
	{ "carnage_4", L"Carnage Mod" },
	{ "caves_1", L"Caves" },
	{ "caveteles_1", L"Cave Teles" },
	{ "caveteles_2", L"Cave Teles" },
	{ "centforce_1", L"Centrifugal Force" },
	{ "centforce_2", L"Centrifugal Force" },
	{ "church_1", L"Church" },
	{ "claust_2", L"Claustrophobia" },
	{ "claust_3", L"Claustrophobia" },
	{ "cliffgulch_1", L"Cliffgulch Tunnels" },
	{ "coagulat_1", L"Coagulation" },
	{ "concrete_1", L"Concretely Cemented, Completely Demented" },
	{ "concrete_2", L"Concretely Cemented, Completely Demented" },
	{ "concrete_3", L"Concretely Cemented, Completely Demented" },
	{ "construct_1", L"Construct" },
	{ "convict_1", L"Convict" },
	{ "convict_2", L"Convict" },
	{ "core_days_2", L"Core Days" },
	{ "coredays_1", L"Core Days" },
	{ "corrupted_1", L"Corrupted" },
	{ "covenantpg_1", L"Covenant Playground" },
	{ "crossguard_1", L"Crossguard" },
	{ "csrhball_1", L"Caesar's Haloball 2015" },
	{ "csrmario_1", L"Caesar's Super Mario Adventure" },
	{ "csrmario_2", L"Caesar's Super Mario Adventure" },
	{ "csrxmas141_1", L"Caesar's Christmas Mod 2014" },
	{ "css101_1", L"CSS 101" },
	{ "ctii_1", L"CTII" },
	{ "ctii_2", L"CTII" },
	{ "ctii_3", L"CTII" },
	{ "ctii_5", L"CTII" },
	{ "ctii_6", L"CTII" },
	{ "cubacity_1", L"Cubacity" },
	{ "darkaether_1", L"Dark Aether" },
	{ "darkaether_2", L"Dark Aether" },
	{ "darkcreek_1", L"Dark Creek" },
	{ "darkcreek_2", L"Dark Creek" },
	{ "deagle_1", L"Deagle6" },
	{ "declare_1", L"Declaration 0x4D610000" },
	{ "deepspace_1", L"Deep Space Arena" },
	{ "delta_ruins_1", L"Delta Ruins" },
	{ "depot_1", L"Depot" },
	{ "depot_3", L"Depot" },
	{ "desertmult_1", L"Desert Multigulch" },
	{ "dgorge1_1", L"Death Gorge" },
	{ "dimension_1", L"Dimensional Planes" },
	{ "downpour_1", L"Downpour" },
	{ "downpour_2", L"Downpour" },
	{ "downpour_3", L"Downpour" },
	{ "downrushh_1", L"Downrush" },
	{ "dragonball_1", L"Haloball Z" },
	{ "drizzle_1", L"Drizzle" },
	{ "drunktank_1", L"Drunk Tank" },
	{ "emsblizz_1", L"Environments Mod Series - Blizzard" },
	{ "emslavapit_1", L"Environments Mod Series - Lava Canyon" },
	{ "erasus_1", L"Erasus" },
	{ "evalpaint_6", L"EVAlution of Paint" },
	{ "evalpaint_8", L"EVAlution of Paint" },
	{ "ewok_1", L"Ewok" },
	{ "farlands_1", L"Farlands" },
	{ "fissure_fall_1", L"Fissure Fall" },
	{ "flatgulch_1", L"Flat Gulch" },
	{ "floodgulch_3", L"Flood Gulch" },
	{ "floodgulch_4", L"Flood Gulch" },
	{ "floodgulch_7", L"Flood Gulch" },
	{ "forestbases_1", L"Forest Bases" },
	{ "frostbite1_1", L"Frostbite" },
	{ "frostbite1_2", L"Frostbite" },
	{ "geomar_ultra_2", L"Geomar Ultra" },
	{ "geomar_ultra_3", L"Geomar Ultra" },
	{ "gladpit_1", L"Gladiator Pit" },
	{ "glasspain_1", L"Glass Pain" },
	{ "glasspain_2", L"Glass Pain" },
	{ "graveyard_1", L"Graveyard" },
	{ "gravimet_1", L"Gravimetrics" },
	{ "greatwall_1", L"Great Wall of Gulch" },
	{ "greenfall_1", L"Greenfall" },
	{ "gwesmultb1_1", L"Galaxy Wars Epic Series" },
	{ "gwesmultc1_3", L"Galaxy Wars Epic Series" },
	{ "gwhp2_1", L"Galaxy Wars - Hangar Preview" },
	{ "h2relic_1", L"Relic" },
	{ "h3valhall_1", L"H3 Valhalla" },
	{ "h3valhall_2", L"H3 Valhalla" },
	{ "halo4css_1", L"Halo 4 CSS" },
	{ "halo4css_2", L"Halo 4 CSS" },
	{ "halo_racers_1", L"Halo Racers" },
	{ "hangem_1", L"HangemHigher" },
	{ "hangie_10", L"HangemHigher" },
	{ "hangie_11", L"HangemHigher" },
	{ "hangie_12", L"HangemHigher" },
	{ "hangie_2", L"HangemHigher" },
	{ "hangie_3", L"HangemHigher" },
	{ "hangie_4", L"HangemHigher" },
	{ "hangie_5", L"HangemHigher" },
	{ "hangie_6", L"HangemHigher" },
	{ "hangie_7", L"HangemHigher" },
	{ "hangie_8", L"HangemHigher" },
	{ "hangie_9", L"HangemHigher" },
	{ "happyhol_1", L"Happy Holidays" },
	{ "happyhol_2", L"Happy Holidays" },
	{ "happyholnomus_1", L"Happy Holidays No Music" },
	{ "haven_1", L"Haven" },
	{ "headlong_1", L"Headlong" },
	{ "headlong_2", L"Headlong" },
	{ "headlong_3", L"Headlong" },
	{ "heatsinks_1", L"Heatsinks" },
	{ "heatsinks_2", L"Heatsinks" },
	{ "heatsinks_3", L"Heatsinks" },
	{ "heatsinks_4", L"Heatsinks" },
	{ "heatsinks_5", L"Heatsinks" },
	{ "heatsinks_6", L"Heatsinks" },
	{ "heh_1", L"Hell Gulch" },
	{ "heh_2", L"Hell Gulch" },
	{ "helix_1", L"Helix Canyon" },
	{ "hemoasis_1", L"Hemoasis" },
	{ "highlow_1", L"High Low" },
	{ "house_1", L"House of the Dead" },
	{ "house_2", L"House of the Dead" },
	{ "huh-what_3_1", L"Huh What 3" },
	{ "hwcanyon_1", L"Halowatch" },
	{ "hwcanyon_2", L"Halowatch" },
	{ "hydra_2", L"Hydra" },
	{ "hydra_3", L"Hydra" },
	{ "hydra_4", L"Hydra" },
	{ "hydra_5", L"Hydra" },
	{ "imminent_1", L"Imminent MD" },
	{ "immure_1", L"Immure" },
	{ "imposing_1", L"Imposing [H3]" },
	{ "imposing_days_1", L"Imposing Days" },
	{ "ipbeta02_1", L"Impactpoint [Beta]" },
	{ "ipbeta03_3", L"Impactpoint [Beta]" },
	{ "ipbeta04_4", L"Impactpoint [Beta]" },
	{ "ipbeta04_5", L"Impactpoint [Beta]" },
	{ "islands_6", L"BattleIslands" },
	{ "islands_7", L"BattleIslands" },
	{ "ivorytower_1", L"Ivory Tower" },
	{ "labyrinth_1", L"Labyrinth" },
	{ "labyrinth_2", L"Labyrinth" },
	{ "labyrinth_3", L"Labyrinth" },
	{ "lock_1", L"Lockout" },
	{ "lock_2", L"Lockout" },
	{ "logplusplus_1", L"Log Mod ++" },
	{ "logxtreme_1", L"Log Mod Extreme" },
	{ "logxtreme_2", L"Log Mod Extreme" },
	{ "matrix_5", L"Matrix" },
	{ "matrix_7", L"Matrix" },
	{ "mgmcollab_1", L"MGM Collab" },
	{ "mgmsuper_1", L"MGM Super Mod" },
	{ "midnightc_1", L"Midnight City" },
	{ "morningdew_1", L"Environments Mod Series - Morning Dew" },
	{ "mountains_1", L"Mountains" },
	{ "mountains_3", L"Mountains" },
	{ "mountains_4", L"Mountains" },
	{ "mountains_5", L"Mountains" },
	{ "mudgorge_1", L"Mudgorge" },
	{ "mudgorge_2", L"Mudgorge" },
	{ "mudgorge_3", L"Mudgorge" },
	{ "mudgorge_4", L"Mudgorge" },
	{ "mudgorge_5", L"Mudgorge" },
	{ "mystic_1", L"Mystic" },
	{ "nightmaps_1", L"Nightmaps" },
	{ "nuclearfal_1", L"Nuclear Fallout" },
	{ "omega_1", L"Omega" },
	{ "outback_1", L"Outback" },
	{ "outback_2", L"Outback" },
	{ "outback_3", L"Outback" },
	{ "outbound_1", L"Outbound" },
	{ "parallax2_1", L"Parallax 2" },
	{ "parallax2_2", L"Parallax 2" },
	{ "parallax_1", L"Parallax Redux" },
	{ "parallax_2", L"Parallax Redux" },
	{ "phoenix2_1", L"Phoenix 2" },
	{ "phoenix2_2", L"Phoenix 2" },
	{ "phoenix2_3", L"Phoenix 2" },
	{ "phoenix2_4", L"Phoenix 2" },
	{ "phoenix2_5", L"Phoenix 2" },
	{ "phoenix2_6", L"Phoenix 2" },
	{ "phoenix2_7", L"Phoenix 2" },
	{ "phoenix2_8", L"Phoenix 2" },
	{ "phoenix2_9", L"Phoenix 2" },
	{ "phoenix3_1", L"Phoenix 3" },
	{ "phoenix3_10", L"Phoenix 3" },
	{ "phoenix3_11", L"Phoenix 3" },
	{ "phoenix3_12", L"Phoenix 3" },
	{ "phoenix3_13", L"Phoenix 3" },
	{ "phoenix3_14", L"Phoenix 3" },
	{ "phoenix3_15", L"Phoenix 3" },
	{ "phoenix3_2", L"Phoenix 3" },
	{ "phoenix3_3", L"Phoenix 3" },
	{ "phoenix3_4", L"Phoenix 3" },
	{ "phoenix3_5", L"Phoenix 3" },
	{ "phoenix3_6", L"Phoenix 3" },
	{ "phoenix3_7", L"Phoenix 3" },
	{ "phoenix3_8", L"Phoenix 3" },
	{ "phoenix3_9", L"Phoenix 3" },
	{ "rainbowroa_1", L"Rainbow Road" },
	{ "rainfora_1", L"Environments Mod Series - Rainforest of Doom" },
	{ "rainforesa_1", L"Environments Mod Series - Rainforest of Joy" },
	{ "rapidfire_1", L"Rapid Fire Action" },
	{ "reachgulch_2", L"Reach Gulch 4" },
	{ "realevolved_1", L"Halo Combat Really Evolved" },
	{ "relicv2_3", L"Relic" },
	{ "rev_war_reload_1", L"Revolutionary War Reloaded" },
	{ "revolution_1", L"Revolutionary War" },
	{ "ricochetbu_1", L"Ricocheting Bullets" },
	{ "rocketsurfinggulch_1", L"Rocket Surfing Gulch" },
	{ "rocketsurfinggulch_2", L"Rocket Surfing Gulch" },
	{ "rswctfodd_1", L"Random Starting Weapons Series - CTF Oddball" },
	{ "ruins2_2", L"Ruins" },
	{ "ruinsv2_7", L"Ruins" },
	{ "sanctuary_7", L"Sanctuary" },
	{ "sandtrap3_1", L"SandTrap 3" },
	{ "satellite_1", L"Satellite" },
	{ "scarynight_1", L"Environments Mod Series - Scary Night" },
	{ "sciophobia_1", L"Sciophobia" },
	{ "scrtsfegpt_1", L"Secrets of Egypt" },
	{ "seaside_1", L"Seaside" },
	{ "seaside_2", L"Seaside" },
	{ "seaside_3", L"Seaside" },
	{ "seaside_4", L"Seaside" },
	{ "seclusion_1", L"Seclusion" },
	{ "shaftkw_1", L"The Shaft" },
	{ "skytwins_1", L"Sky Twins" },
	{ "slipnslide_1", L"Slip 'N Slide" },
	{ "sneak_1", L"Sneak" },
	{ "snow_drop_1", L"Snow Drop" },
	{ "snowgulch_1", L"Snow Gulch" },
	{ "snowgulch_2", L"Snow Gulch" },
	{ "snownatur_1", L"Snow Nature" },
	{ "snowpact_6", L"Impactpoint [Beta]" },
	{ "snowpact_7", L"Impactpoint [Beta]" },
	{ "snowynight_1", L"Environments Mod Series - Snowy Night" },
	{ "solitude_1", L"Solitude" },
	{ "spaceslope_1", L"Space Slopes" },
	{ "spartrain_2", L"Spar Training" },
	{ "spew_1", L"Spew" },
	{ "sphere_1", L"Sphere" },
	{ "starlight_1", L"Starlight Arena" },
	{ "starlight_2", L"Starlight Arena" },
	{ "starwarsb_1", L"Halo Star Wars" },
	{ "starwarsb_3", L"Halo Star Wars" },
	{ "sticksandstones_1", L"Sticks and Stones" },
	{ "sticksandstones_2", L"Sticks and Stones" },
	{ "sunset_1", L"Sunset" },
	{ "sunset_2", L"Sunset" },
	{ "sunset_3", L"Sunset" },
	{ "sunset_4", L"Sunset" },
	{ "sunset_5", L"Sunset" },
	{ "sunset_6", L"Sunset" },
	{ "sunset_7", L"Sunset" },
	{ "talloniv_1", L"Tallon IV" },
	{ "telepara_1", L"Teleporter Paradise" },
	{ "tempo_1", L"Tempo" },
	{ "tensity_1", L"Tensity" },
	{ "thefactory_1", L"The Factory" },
	{ "thegrid_1", L"The Grid" },
	{ "theisland_3", L"The Island" },
	{ "triforce_1", L"Triforce" },
	{ "tscemp_1", L"Silent Cartographer Evolved Multiplayer Mod" },
	{ "turf2_1", L"Turf" },
	{ "urban_tactics_3", L"Urban Tactics" },
	{ "valhalla_days_2", L"Valhalla Days" },
	{ "valhalla_days_3", L"Valhalla Days" },
	{ "vast_1", L"Vast" },
	{ "volcanoyo_1", L"Volcano" },
	{ "warlock_1", L"Warlock" },
	{ "wasteland_1", L"Wasteland" },
	{ "wasteland_3", L"Wasteland" },
	{ "we_1", L"Weapons Evolved" },
	{ "weapshootwe_1", L"Weapons Shoot Weapons" },
	{ "whirlwind_1", L"Whirlwind" },
	{ "whirlwind_2", L"Whirlwind" },
	{ "wolvesamb_1", L"Wolves Ambush" },
	{ "wolvesamb_2", L"Wolves Ambush" },
	{ "xmascreek_1", L"Christmas Creek" },
	{ "yoyorast_1", L"Yoyorast Island" },
	{ "yoyorast_2", L"Yoyorast Island" },
	{ "yoyorastv2_1", L"Yoyorast Island v2" },
	{ "za_1", L"Zombie Apocalypse" },
	{ "zanzibar_1", L"Zanzibar" },
	{ "zerohourh_1", L"Zerohour" },
	{ "zmpsierra_1", L"ZMP Sierra" },
};
